language: php
cache:
  bundler: true
  apt: true
  directories:
  - vendor
php:
- 5.5
mysql:
  database: drupal
  username: root
  encoding: utf8
install:
- sudo apt-get update > /dev/null
- composer selfupdate
- mysql -e 'SET GLOBAL wait_timeout = 5400;'
- mysql -e "SHOW VARIABLES LIKE 'wait_timeout'"
- echo 'max_execution_time = 120' >> drupal.php.ini;
- echo 'sendmail_path = /bin/true' >> drupal.php.ini;
- phpenv config-add drupal.php.ini
- phpenv rehash
- composer global require drush/drush:6.*
- export PATH="$HOME/.composer/vendor/bin:$PATH"
- git clone --branch 8.x-1.x git@github.com:nateswart/composer.git ~/.drush/composer
- drush dl drupal --default-major=7 -y
- mv drupal-* drupal
- mv composer.json drupal/profiles/standard/.
- mkdir -p drupal/sites/all/modules/contrib/lightning_features
- mv lightning_* drupal/sites/all/modules/contrib/lightning_features/.
- ls -l
- cd drupal
- drush make --no-core sites/all/modules/contrib/lightning_features/lightning_features.make -y
- drush si standard --db-url=mysql://root:@localhost/drupal -y
before_script:
- drush en lightning_* -y
- drush dis dblog -y
- drush vset composer_manager_autobuild_file 0
- drush vset composer_manager_autobuild_packages 0
- drush en composer_manager -y
- travis_wait drush composer-manager install -n --prefer-source
- drush vset composer_manager_autobuild_file 1
- drush vset composer_manager_autobuild_packages 1
- travis_wait drush en behatrunner -l http://127.0.0.1:8080 -y
- drush cc all
- drush runserver --server=builtin 8080 &
- sleep 4
script:
- drush brun -l http://127.0.0.1:8080 -v
notifications:
  slack:
    secure: FLlgKwSonE7A1O9mguUmTQwiRo03adA6xsNx/Cd537xPq0RVE7+kUdFXlh7l6ff3y5Zamk7QcPpqmDa10zSqQxLqDdfmZqOPK7Ug8SEYGpRxHBzCxOV0dhBperkxPWaxgfOGG7INxItFrXASYMrjC38SrVF8IFi6M3XV80LS9kY=
matrix:
  fast_finish: true
after_failure:
- sudo chmod -Rv 777 build/logs/*
- bundle install --without development
- travis-artifacts upload --path build/logs --target-path artifacts/$TRAVIS_BUILD_ID/$TRAVIS_JOB_ID
