<?php
/**
 * @file
 * Code for the Virgin Base feature.
 */

include_once 'virgin_base.features.inc';

/**
 * Implements hook_element_info_alter().
 */
function virgin_base_element_info_alter(&$elements) {
  if (!empty($elements['link_field'])) {
    $elements['link_field']['#process'][] = 'virgin_base_link_field_process';
  }
}

/**
 * Implements hook_field_attach_validate().
 */
function virgin_base_field_attach_validate($entity_type, $entity, &$errors) {
  // Make field_cta_links url required if title is not empty and virgin_type
  // field has link option selected
  if (!empty($entity->field_cta_links[LANGUAGE_NONE])) {
    foreach ($entity->field_cta_links[LANGUAGE_NONE] as $delta => $cta_link) {
      if ($cta_link['attributes']['virgin_type'] == 'link' && !empty($cta_link['title']) && empty($cta_link['url'])) {
        $errors['field_cta_links'][LANGUAGE_NONE][$delta][] = array(
          'error' => 'link_required',
          'message' => t('Url must be provided with Link type'),
          'error_element' => array('url' => TRUE),
        );
      }
    }
  }
}

/**
 * Implements hook_form_FORM_ID_alter() for fieldable_panels_panes_fieldable_panels_pane_content_type_edit_form.
 *
 * Modifies the fieldable panel panes edit form for improved editing interface.
 */
function virgin_base_form_fieldable_panels_panes_fieldable_panels_pane_content_type_edit_form_alter(&$form, &$form_state, $form_id) {
  $form['extra_config'] = array(
    '#type' => 'fieldset',
    '#title' => t('Extra Configuration'),
    '#collapsible' => TRUE,
    '#collapsed' => TRUE,
    '#tree' => FALSE,
    '#group' => 'additional_settings',
    '#weight' => 100
  );

  $move_to_extra = array(
    'view_mode',
    'link',
    'language'
  );

  foreach ($move_to_extra as $field_name) {
    $form['extra_config'][$field_name] = $form[$field_name];
    unset($form[$field_name]);
  }
}

// Helpers
// ----------------------------------------------------------------------------

/**
 * Convert the link field class to a select
 *
 * @see link_field_process
 */
function virgin_base_link_field_process($element, $form_state, $complete_form) {
  // The supported link fields to override class textfield with a select list
  $supported = array(
    'field_cta_links'
  );

  // If current element is not on supported list do not make changes
  if (!in_array($element['#field_name'], $supported)) {
    return $element;
  }

  // Field brand color has the virgin brand colors
  $field = field_info_field('field_brand_color');

  // Extra button color options not covered by brand colors
  $options = array(
    '' => t('Default'),
    'transparent' => t('Transparent'),
    'orange' => t('Solid Orange'),
    'link' => t('Link'),
    'outline-black' => t('Outline-black'),
    'outline-white' => t('Outline-white'),
  );

  // Append gradient prefix to all brand colors
  foreach ($field['settings']['allowed_values'] as $key => $value) {
    $options['gradient-' . $key] = $value;
  }

  // Load element attributes
  $attributes = empty($element['#value']['attributes']) ? '' : $element['#value']['attributes'];

  // Add a new field to choose the button style
  $element['attributes']['virgin_class'] = array(
    '#type' => 'select',
    '#title' => t('Button Style'),
    '#options' => empty($options) ? array() : $options,
    '#default_value' => isset($attributes['virgin_class']) ? $attributes['virgin_class'] : '',
  );

  // The type field options
  $types = array(
    'link' => 'Link',
    'get_in_touch' => 'Get in Touch',
    'register_interest' => 'Register Interest'
  );

  // Generate a unique id for this field to add #states based on it
  $id = drupal_html_id('link_' . $element['#field_name'] . '_attributes_virgin_type_ ' . $element['#delta']);

  // Add a new field to choose between a link field and CTA buttons
  $element['attributes']['virgin_type'] = array(
    '#type' => 'select',
    '#title' => t('Type'),
    '#options' => $types,
    '#default_value' => isset($attributes['virgin_type']) ? $attributes['virgin_type'] : '',
    '#attributes' => array(
      'id' => $id,
    ),
  );

  // Show url field if virgin_type value is link
  $element['url']['#states'] = array(
    // Hide the settings when the cancel notify checkbox is disabled.
    'visible' => array(
      '#' . $id => array('value' => 'link'),
    )
  );

  return $element;
}
