<?php

/**
 * @file
 * Contains administration page callbacks and forms for virgin_sync module.
 */

/**
 * Batch sync confirmation form
 */
/*function virgin_sync_admin_confirm_sync_form($form, $form_state) {
  $form['info'] = array(
    '#prefix' => t('<h3>Sync Content</h3>'),
    '#suffix' => t('<p>Depending on the number of items to be synced this process can take a few minutes. Once this process has started please wait until it is finished.</p>')
  );

  $form['submit'] = array(
    '#type' => 'submit',
    '#value' => t('Start Sync'),
    '#id' => 'edit-submit'
  );

  return $form;
}*/

/**
 * Submit callback for virgin_sync_admin_confirm_sync_form form
 */
/*function virgin_sync_admin_confirm_sync_form_submit() {

  // Execute the sync batch operation on submit
  virgin_sync_batch();
}*/
