<?php
/**
 * @file
 * Handles drush integration for Virgin Sync module.
 */

/**
 * Implements hook_drush_command().
 */
/*function virgin_sync_drush_command() {
  $items = array();

  $items['virgin-sync'] = array(
    'description' => "Synchronizes external content to Drupal.",
    'arguments' => array(),
    'options' => array(),
    'examples' => array(),
    'aliases' => array(),
    'bootstrap' => DRUSH_BOOTSTRAP_FULL,
  );

  return $items;
}*/

/**
 * Executes drush virgin-sync command.
 */
/*function drush_virgin_sync() {
  drush_print("Initiating synchronization.");
  virgin_sync_batch();
  drush_backend_batch_process();
}*/
