<?php

/**
 * @file
 * Main file for virgin_attendly module.
 */

/**
 * Implements hook_menu().
 */
function virgin_attendly_menu() {
  $items = array();

  $items['virgin-attendly/webhooks/%'] = array(
    'title' => 'Virgin Attendly Webhooks',
    'page callback' => 'virgin_attendly_webhooks',
    'access callback' => 'virgin_attendly_webhooks_access',
    'access arguments' => array(2),
    'type' => MENU_CALLBACK
  );

  return $items;
}

/**
 * Access callback for webhooks
 *
 * @param $token
 *  The webhooks security access token.
 * @return bool
 *  TRUE access is granted, FALSE otherwise.
 */
function virgin_attendly_webhooks_access($token) {
  if (!empty($token) && variable_get('attendly_webhooks_token') === $token) {
    return TRUE;
  }

  return FALSE;
}

/**
 * Page callback for webhooks
 */
function virgin_attendly_webhooks() {
  $input = file_get_contents('php://input');
  $data = json_decode($input);

  // todo implement me
}
