<?php
/**
 * @file
 * Code for the Virgin Festival feature.
 */

include_once 'virgin_festival.features.inc';

/**
 * Implements hook_menu().
 */
function virgin_festival_menu() {
  $items = array();

  $items['node/%node/tickets'] = array(
    'title' => 'Tickets',
    'page callback' => 'virgin_festival_page_tickets',
    'page arguments' => array(1),
    'access callback' => TRUE,
    'type' => MENU_CALLBACK,
    'file' => 'virgin_festival.pages.inc'
  );

  return $items;
}

/**
 * Implements hook_theme().
 */
function virgin_festival_theme($existing, $type, $theme, $path) {
  return array(
    'virgin_festival__tickets' => array(
      'template' => 'virgin_festival__tickets',
      'variables' => array(
        'iframe_url' => '',
        'header' => '',
        'subnav' => '',
      )
    )
  );
}

/**
 * Implements hook_form_FORM_ID_alter().
 */
function virgin_festival_form_festival_node_form_alter(&$form, &$form_state) {
  // As this field will be handled by the system remove it from ui form
  $form['field_festival_state']['#access'] = FALSE;
}

/**
 * Implements hook_virgin_sync_handlers().
 */
function virgin_festival_virgin_sync_handlers() {
  return array(
    new VirginFestivalSyncHandler()
  );
}
