<?php
/**
 * @file
 * Code for the Virgin Components feature.
 */

include_once 'virgin_components.features.inc';

/**
 * Implements hook_ctools_plugin_directory().
 */
function virgin_components_ctools_plugin_directory($module, $plugin) {
  if (in_array($module, array('panels', 'panelizer', 'ctools', 'page_manager'))) {
    return 'plugins/' . $plugin;
  }
}

/**
 * Implements hook_theme().
 *
 * This need to be added so that we can override default fieldable_panel_panes
 * and paragraphs items hook suggestions
 *
 * @see virgin_components_preprocess()
 */
function virgin_components_theme() {
  return array(
    'virgin_components' => array(
      'render element' => 'elements',
      'template'  => 'virgin-components',
    ),
    'virgin_components__ct__festival-header' => array(
      'variables' => array(),
      'template' => 'virgin-components__ct__festival-header',
    ),
    'virgin_components__ct__subnav' => array(
      'variables' => array(),
      'template' => 'virgin-components__ct__subnav',
    ),
  );
}

/**
 * Implements hook_preprocess().
 */
function virgin_components_preprocess(&$variables) {
  // The supported hooks list
  $supported = array(
    'paragraphs_item',
    'fieldable_panels_pane'
  );

  // If hook is not supported bail out
  if (empty($variables['elements']['#entity_type']) || !in_array($variables['elements']['#entity_type'], $supported)) {
    return;
  }

  // Loop between components list and if any of the components supports this
  // entity_type and bundle preprocess it and override theme suggestion
  foreach (virgin_components_list() as $component) {
    if ($component->supports($variables['elements']['#entity_type'], $variables['elements']['#bundle'])) {
      $component->preProcess($variables);

      $variables['theme_hook_suggestions'] = array($component->themeSuggestion());
    }
  }
}

// Helpers
// ----------------------------------------------------------------------------

/**
 * Get list of components
 *
 * @return VirginComponentsInterface[]
 */
function virgin_components_list() {
  $list = &drupal_static(__FUNCTION__);

  if (empty($list)) {
    $list = array(
      // Fieldable Panel Panes Handlers
      new VirginComponentHeroEventCard(),
      new VirginComponentAccordion(),
      new VirginComponentBasicContentBlock(),
      new VirginComponentPromotionalBanner(),
      new VirginComponentTeaserBlock(),
      new VirginComponentHeroBannerBlock(),
      new VirginComponentCTABlock(),
      new VirginComponentTicketCards(),
      new VirginComponentPackageCards(),
      new VirginComponentUntimedEventCards(),
      new VirginComponentCarousel(),
      new VirginComponentPhotoGallery(),
      new VirginComponentVideoBlock(),
      new VirginComponentHootsuiteSocialFeed(),
      new VirginComponentGamefacePhotoGallery(),
      new VirginComponentMyLapsTrackMyRunner(),

      // Paragraphs Handlers
      new VirginComponentEventFestivalBannerItem(),
      new VirginComponentTeaserItem(),
      new VirginComponentCTABlockItem(),
      new VirginComponentTicketCardItem(),
      new VirginComponentPackageCardItem(),
      new VirginComponentCustomBannerItem(),
      new VirginComponentUntimedEventCardItem(),
      new VirginComponentSlideItem(),
      new VirginComponentAccordionItem(),
    );
  }

  return $list;
}
