
// Components
import vsBasket from './components/vs-basket';
import vsContactForm from './components/vs-contact-form';
import vsCountDown from './components/vs-countdown';
import vsHeader from './components/vs-header';
import vsIFrame from './components/vs-iframe';
import vsIPE from './components/vs-ipe';
import vsOutline from './components/vs-outline';
import vsRegion from './components/vs-region';
import vsSharer from './components/vs-sharer';
import vsVideoBanner from './components/vs-video-banner';
import vsStickyBasket from './components/vs-sticky-basket';
import vsBar from './components/vs-bar';
import vsSubnav from './components/vs-subnav';
import vsUserLogin from './components/vs-user-login';
import vsUserPassword from './components/vs-user-password';
import vsUserPasswordReset from './components/vs-user-password-reset';
import vsUserProfile from './components/vs-user-profile';
import vsUserRegister from './components/vs-user-register';
import vsImage from './components/vs-image';
import vsVideo from './components/vs-video';
import vsCookie from './components/vs-cookie';
import vsNotification from './components/vs-notification';
import vsHeroBanner from './components/vs-heroBanner';
import vsGtm from './components/vs-gtm';
import vsCarousel from './components/vs-carousel';
import vsScroller from './components/vs-scroller';
import vsPhotoGallery from './components/vs-photo-gallery';
import vsUserMenu from './components/vs-user-menu';
import vsDetectMobile from './components/vs-detect-mobile';
import vsResults from './components/vs-results';
import vsUserTicket from './components/vs-user-ticket';
import vsCtaLinks from './components/vs-cta-links';

vsBasket();
vsContactForm();
vsCountDown();
vsHeader();
vsIFrame();
vsIPE();
vsOutline();
vsRegion();
vsSharer();
vsVideoBanner();
vsStickyBasket();
vsBar();
vsSubnav();
vsUserLogin();
vsUserPassword();
vsUserPasswordReset();
vsUserProfile();
vsUserRegister();
vsImage();
vsVideo();
vsCookie();
vsNotification();
vsHeroBanner();
vsGtm();
vsCarousel();
vsScroller();
vsPhotoGallery();
vsUserMenu();
vsDetectMobile();
vsResults();
vsUserTicket();
vsCtaLinks();

// Libs
import bootstrap from './lib/bootstrap';

bootstrap();
