<?php
/**
 * @file
 * Code for the Virgin User feature.
 */

include_once 'virgin_user.features.inc';

/**
 * Implements hook_username_alter().
 */
function virgin_user_username_alter(&$name, $account) {

  // Set the visible username from the user's given name and surname.
  if ($account->uid) {
    $account_wrapper = entity_metadata_wrapper('user', $account);
    $given_name = $account_wrapper->field_given_name->value();
    $surname = $account_wrapper->field_surname->value();
    $full_name = trim($given_name . ' ' . $surname);

    // In some cases, such as the user administration view, the account object
    // might not be fully loaded. In those cases, fallback to the username with
    // the user ID.
    if (empty($full_name)) {
      $name = '(' . $account->uid . ') ' . $name;
    }
  }
}

/**
 * Implements hook_form_FORM_ID_alter() for user_profile_form.
 */
function virgin_user_form_user_profile_form_alter(&$form, &$form_state, $form_id) {

  // The user cannot change his SugarCRM ID as this is entirely
  // managed automatically by the system.
  $form['field_sugar_id']['#access'] = FALSE;
}
