<?php
/**
 * @file
 * Code for the Virgin Package feature.
 */

include_once 'virgin_package.features.inc';

/**
 * Implements hook_form_FORM_ID_alter().
 */
/*function virgin_package_form_package_node_form_alter(&$form, &$form_state) {
  // As this field will be handled by the system prevent it from being modified
  $form['field_package_state']['#disabled'] = TRUE;
}*/

/**
 * Implements hook_virgin_sync_handlers().
 */
/*function virgin_package_virgin_sync_handlers() {
  return array(
    new VirginPackageSyncHandler()
  );
}*/
