<?php

/**
 * Defines virginsport panels layout.
 */

$plugin = array(
  'title' => t('Virgin Sport'),
  'category' => t('VirginSport'),
  'icon' => 'icon.png',
  'theme' => 'virginsport',
  'admin css' => 'virginsport.admin.css',
  'regions' => array(
    'first' => t('1st'),
    'second' => t('2nd'),
    'third' => t('3rd'),
    'fourth' => t('4th'),
    'fifth' => t('5th'),
    'sixth' => t('6th'),
    'seventh' => t('7th'),
    'eighth' => t('8th'),
    'nineth' => t('9th'),
    'tenth' => t('10th'),
  ),
);
